version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sqs
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1

  dynamodb-init:
    image: amazon/aws-cli
    depends_on:
      - localstack
    volumes:
      - ./create_dynamodb_table.sh:/docker-entrypoint-initaws.d/create_dynamodb_table.sh
    entrypoint: /bin/bash /docker-entrypoint-initaws.d/create_dynamodb_table.sh
    environment:
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack

